In [1]:
# Preprocessing Methods

In [2]:
import pandas as pd
import numpy as np

C:\Users\ACER\anaconda31\lib\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (


In [3]:
# Sample Dataset

data = {'City': ['City A', 'City B', 'City C', 'City D'],
         'Temperature_F': [75,82,68,56]}

In [4]:
data

{'City': ['City A', 'City B', 'City C', 'City D'],
 'Temperature_F': [75, 82, 68, 56]}

In [5]:
df = pd.DataFrame(data)

In [6]:
df

City  Temperature_F
0  City A             75
1  City B             82
2  City C             68
3  City D             56

In [7]:
df['Temp_c'] = (df['Temperature_F']-32)*5/9

In [8]:
print("\n Transformed data : ")
print(df)


 Transformed data : 
     City  Temperature_F     Temp_c
0  City A             75  23.888889
1  City B             82  27.777778
2  City C             68  20.000000
3  City D             56  13.333333


In [9]:
data = {'Values' : [10,50,100,200,500]}

In [10]:
data

{'Values': [10, 50, 100, 200, 500]}

In [11]:
df = pd.DataFrame(data)

In [12]:
df

Values
0      10
1      50
2     100
3     200
4     500

In [13]:
# Linear Regression

# Assumption

# X & Y variables should be correlated to each other  - A-1

# X1 & X2 can not be correlated - Multicollinearity problem

# Y = Bo + B1X1 + B2X2 + B3X3 + B4X4

# Y = ?   The Price of a Toyoto Car

#X1 - CC Power
#X2 - No. of Airbags
#X3 - No. of Kms
#X4 - The Size of Car
#X5 - The Name of owner

# Correlation for X5 & Y - Its O (Not required that is why we need preprocessing)



In [14]:
df.describe()

Values
count    5.000000
mean   172.000000
std    196.646892
min     10.000000
25%     50.000000
50%    100.000000
75%    200.000000
max    500.000000

In [15]:
df['Log_values'] = np.log(df['Values'])

In [16]:
df.describe()

Values  Log_values
count    5.000000    5.000000
mean   172.000000    4.466541
std    196.646892    1.479612
min     10.000000    2.302585
25%     50.000000    3.912023
50%    100.000000    4.605170
75%    200.000000    5.298317
max    500.000000    6.214608

In [17]:
df['sqrt'] = np.sqrt(df['Values'])

In [18]:
df

Values  Log_values       sqrt
0      10    2.302585   3.162278
1      50    3.912023   7.071068
2     100    4.605170  10.000000
3     200    5.298317  14.142136
4     500    6.214608  22.360680

In [19]:
from scipy.stats import boxcox

In [20]:
df['box'],_ = boxcox(df['Values'])

In [21]:
df

Values  Log_values       sqrt        box
0      10    2.302585   3.162278   2.787192
1      50    3.912023   7.071068   5.448353
2     100    4.605170  10.000000   6.824622
3     200    5.298317  14.142136   8.363309
4     500    6.214608  22.360680  10.679487

In [22]:
# Standardization -- trying to squeeze the data to get in same scale

In [23]:
# Generally preferred
from sklearn.preprocessing import StandardScaler

In [24]:
df = pd.DataFrame(np.random.rand(6,3))

In [25]:
df

0         1         2
0  0.462192  0.123244  0.609268
1  0.973167  0.173667  0.473018
2  0.643646  0.343651  0.442535
3  0.350863  0.132358  0.766604
4  0.985179  0.473458  0.586462
5  0.008114  0.888449  0.065294

In [26]:
scaler = StandardScaler()
scaler.fit(df)

StandardScaler()

In [27]:
df.describe()

0         1         2
count  6.000000  6.000000  6.000000
mean   0.570527  0.355804  0.490530
std    0.378338  0.294919  0.237888
min    0.008114  0.123244  0.065294
25%    0.378695  0.142685  0.450156
50%    0.552919  0.258659  0.529740
75%    0.890787  0.441006  0.603566
max    0.985179  0.888449  0.766604

In [28]:
Standardized = scaler.transform(df)

In [29]:
Standardized.mean()

-8.635067969306773e-17

In [30]:
data = {'Feature1' : [2,4,5,7,8,9], 'Feature2' : [10,20,15,25,20,35]}

In [31]:
df = pd.DataFrame(data)
df

Feature1  Feature2
0         2        10
1         4        20
2         5        15
3         7        25
4         8        20
5         9        35

In [32]:
df.describe()

Feature1   Feature2
count  6.000000   6.000000
mean   5.833333  20.833333
std    2.639444   8.612007
min    2.000000  10.000000
25%    4.250000  16.250000
50%    6.000000  20.000000
75%    7.750000  23.750000
max    9.000000  35.000000

In [33]:
Scaler = StandardScaler()
scaler.fit(df)

StandardScaler()

In [34]:
Standardized_data = scaler.transform(df)

In [35]:
Standardized_df = pd.DataFrame(Standardized_data, columns = df.columns)

In [36]:
Standardized_df

Feature1  Feature2
0 -1.590943 -1.377997
1 -0.760886 -0.106000
2 -0.345857 -0.741999
3  0.484200  0.529999
4  0.899229 -0.106000
5  1.314257  1.801996

In [37]:
# i ~ N(Mean = 0, SD =1)

In [38]:
import seaborn as sns

In [39]:
iris = sns.load_dataset('iris')

In [40]:
iris.head(5)

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [41]:
x = iris.select_dtypes(include=['float64', 'int64'])

In [42]:
from sklearn.preprocessing import StandardScaler

In [43]:
scaler  = StandardScaler()

In [44]:
scaler.fit(x)

StandardScaler()

In [45]:
Standardized = scaler.transform(x)

In [46]:
Standardized

array([[-9.00681170e-01,  1.01900435e+00, -1.34022653e+00,
        -1.31544430e+00],
       [-1.14301691e+00, -1.31979479e-01, -1.34022653e+00,
        -1.31544430e+00],
       [-1.38535265e+00,  3.28414053e-01, -1.39706395e+00,
        -1.31544430e+00],
       [-1.50652052e+00,  9.82172869e-02, -1.28338910e+00,
        -1.31544430e+00],
       [-1.02184904e+00,  1.24920112e+00, -1.34022653e+00,
        -1.31544430e+00],
       [-5.37177559e-01,  1.93979142e+00, -1.16971425e+00,
        -1.05217993e+00],
       [-1.50652052e+00,  7.88807586e-01, -1.34022653e+00,
        -1.18381211e+00],
       [-1.02184904e+00,  7.88807586e-01, -1.28338910e+00,
        -1.31544430e+00],
       [-1.74885626e+00, -3.62176246e-01, -1.34022653e+00,
        -1.31544430e+00],
       [-1.14301691e+00,  9.82172869e-02, -1.28338910e+00,
        -1.44707648e+00],
       [-5.37177559e-01,  1.47939788e+00, -1.28338910e+00,
        -1.31544430e+00],
       [-1.26418478e+00,  7.88807586e-01, -1.22655167e+00,
      

In [47]:
from sklearn.preprocessing import StandardScaler 
num_col = iris.select_dtypes(include=['float64', 'int64']).columns 
scaler = StandardScaler() 
standard = scaler.fit(iris[num_col]) 
iris_scaled = pd.DataFrame(scaler.transform(iris[num_col]), columns=num_col) 
iris_scaled

sepal_length  sepal_width  petal_length  petal_width
0       -0.900681     1.019004     -1.340227    -1.315444
1       -1.143017    -0.131979     -1.340227    -1.315444
2       -1.385353     0.328414     -1.397064    -1.315444
3       -1.506521     0.098217     -1.283389    -1.315444
4       -1.021849     1.249201     -1.340227    -1.315444
..            ...          ...           ...          ...
145      1.038005    -0.131979      0.819596     1.448832
146      0.553333    -1.282963      0.705921     0.922303
147      0.795669    -0.131979      0.819596     1.053935
148      0.432165     0.788808      0.933271     1.448832
149      0.068662    -0.131979      0.762758     0.790671

[150 rows x 4 columns]

In [48]:
## Same thing as in above lines
cols = iris.select_dtypes(include='number').columns 
# get numerical columns with data 
num_iris = iris[cols] 
# Standardadize values 
standard_data = scaler.fit_transform(num_iris) 
# convert to Dataframe 
std_df = pd.DataFrame(standard_data, columns=cols) 
from IPython.display import display 
display(pd.concat([iris, std_df], axis=1))

sepal_length  sepal_width  petal_length  petal_width    species  \
0             5.1          3.5           1.4          0.2     setosa   
1             4.9          3.0           1.4          0.2     setosa   
2             4.7          3.2           1.3          0.2     setosa   
3             4.6          3.1           1.5          0.2     setosa   
4             5.0          3.6           1.4          0.2     setosa   
..            ...          ...           ...          ...        ...   
145           6.7          3.0           5.2          2.3  virginica   
146           6.3          2.5           5.0          1.9  virginica   
147           6.5          3.0           5.2          2.0  virginica   
148           6.2          3.4           5.4          2.3  virginica   
149           5.9          3.0           5.1          1.8  virginica   

     sepal_length  sepal_width  petal_length  petal_width  
0       -0.900681     1.019004     -1.340227    -1.315444  
1       -1.143017    -0.131979     -1.340227    -1.315444  
2       -1.385353     0.328414     -1.397064    -1.315444  
3       -1.506521     0.098217     -1.283389    -1.315444  
4       -1.021849     1.249201     -1.340227    -1.315444  
..            ...          ...           ...          ...  
145      1.038005    -0.131979      0.819596     1.448832  
146      0.553333    -1.282963      0.705921     0.922303  
147      0.795669    -0.131979      0.819596     1.053935  
148      0.432165     0.788808      0.933271     1.448832  
149      0.068662    -0.131979      0.762758     0.790671  

[150 rows x 9 columns]

In [49]:
import seaborn as sns

from sklearn.preprocessing import StandardScaler

 

iris = sns.load_dataset('iris')

 

print("Original Dataset:")

print(iris.head())

 

numeric_columns = iris.select_dtypes(include='number').columns

 

scaler = StandardScaler()

iris[numeric_columns] = scaler.fit_transform(iris[numeric_columns])

 

print("\nTransformed Dataset:")

print(iris.head())



Original Dataset:
   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

Transformed Dataset:
   sepal_length  sepal_width  petal_length  petal_width species
0     -0.900681     1.019004     -1.340227    -1.315444  setosa
1     -1.143017    -0.131979     -1.340227    -1.315444  setosa
2     -1.385353     0.328414     -1.397064    -1.315444  setosa
3     -1.506521     0.098217     -1.283389    -1.315444  setosa
4     -1.021849     1.249201     -1.340227    -1.315444  setosa


In [50]:
# Two distances:

# Euclidean distance -- Sensitive to scale

# Standard Euclidean Distance -- Not Sensitive to scale

In [51]:
# Normalisation

In [52]:
from sklearn.preprocessing import MinMaxScaler

In [53]:
data1 = {'Feature1' : [2,4,5,7,8,9], 'Feature2' : [10,20,15,25,20,35]}

In [54]:
df1 = pd.DataFrame(data1)
df1

Feature1  Feature2
0         2        10
1         4        20
2         5        15
3         7        25
4         8        20
5         9        35

In [55]:
# Normalisation applying

In [56]:
scaler = MinMaxScaler()
normalised_data = scaler.fit_transform(df1)



In [57]:
df_normalised = pd.DataFrame(normalised_data, columns = df1.columns)
df_normalised

Feature1  Feature2
0  0.000000       0.0
1  0.285714       0.4
2  0.428571       0.2
3  0.714286       0.6
4  0.857143       0.4
5  1.000000       1.0

In [58]:
# Same method for normalize in short 

from sklearn.preprocessing import minmax_scale

In [59]:
normalised = minmax_scale(df)

In [60]:
normalised

array([[0.        , 0.        ],
       [0.28571429, 0.4       ],
       [0.42857143, 0.2       ],
       [0.71428571, 0.6       ],
       [0.85714286, 0.4       ],
       [1.        , 1.        ]])

In [61]:
import pandas as pd
from sklearn.preprocessing import StandardScaler, MinMaxScaler
# Sample dataset
data = {'Age': [25, 30, 35, 40, 45],
        'Income': [50000, 60000, 75000, 100000, 120000]}
df = pd.DataFrame(data)
# Display the original dataset
print("Original Dataset:")
print(df)
# Standardization
scaler_standardization = StandardScaler()
df_standardized = pd.DataFrame(scaler_standardization.fit_transform(df), columns=df.columns)
# Normalization
scaler_normalization = MinMaxScaler()
df_normalized = pd.DataFrame(scaler_normalization.fit_transform(df), columns=df.columns)
# Display the standardized dataset
print("\nStandardized Dataset:")
print(df_standardized)
# Display the normalized dataset
print("\nNormalized Dataset:")
print(df_normalized)

Original Dataset:
   Age  Income
0   25   50000
1   30   60000
2   35   75000
3   40  100000
4   45  120000

Standardized Dataset:
        Age    Income
0 -1.414214 -1.203033
1 -0.707107 -0.814958
2  0.000000 -0.232845
3  0.707107  0.737343
4  1.414214  1.513494

Normalized Dataset:
    Age    Income
0  0.00  0.000000
1  0.25  0.142857
2  0.50  0.357143
3  0.75  0.714286
4  1.00  1.000000


In [87]:
# One - Hot Encoding --- Converting the categorical variables to numerical variables

# Problem -- It will increase the dimentionality (increase the number of columns)

# Dummy variable trap

# Always create n-1 dummy variables

In [63]:
Size = ['Small', 'Medium', 'Large', 'XL']

In [64]:
Color = ['Red' 'White', 'Black']

In [65]:
pd.get_dummies

<function pandas.core.reshape.encoding.get_dummies(data, prefix=None, prefix_sep: 'str | Iterable[str] | dict[str, str]' = '_', dummy_na: 'bool' = False, columns=None, sparse: 'bool' = False, drop_first: 'bool' = False, dtype: 'NpDtype | None' = None) -> 'DataFrame'>

In [66]:
data = {'Color' : ['Red', 'Blue', 'Green', 'Red', 'Green']}

In [67]:
df = pd.DataFrame(data)
df

Color
0    Red
1   Blue
2  Green
3    Red
4  Green

In [68]:
df_encoded = pd.get_dummies(df, columns = ['Color'], prefix = 'color')

In [69]:
df_encoded

color_Blue  color_Green  color_Red
0       False        False       True
1        True        False      False
2       False         True      False
3       False        False       True
4       False         True      False

In [70]:
# Curse of dimentionality

In [71]:
from sklearn.preprocessing import OneHotEncoder

In [72]:
Color = ['Red' 'White', 'Black']
Color = np.array(Color).reshape(-1,1)

encoder = OneHotEncoder(sparse_output = False)
encoder = encoder.fit_transform(Color)

In [73]:
encoder


array([[0., 1.],
       [1., 0.]])

In [77]:
import seaborn as sns
iris = sns.load_dataset('iris')

In [78]:
iris.head(5)

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [88]:
iris['species'].value_counts()

species
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64

In [89]:
a = pd.get_dummies(iris, columns = ['species'], drop_first = True)

In [90]:
a

sepal_length  sepal_width  petal_length  petal_width  species_versicolor  \
0             5.1          3.5           1.4          0.2               False   
1             4.9          3.0           1.4          0.2               False   
2             4.7          3.2           1.3          0.2               False   
3             4.6          3.1           1.5          0.2               False   
4             5.0          3.6           1.4          0.2               False   
..            ...          ...           ...          ...                 ...   
145           6.7          3.0           5.2          2.3               False   
146           6.3          2.5           5.0          1.9               False   
147           6.5          3.0           5.2          2.0               False   
148           6.2          3.4           5.4          2.3               False   
149           5.9          3.0           5.1          1.8               False   

     species_virginica  
0                False  
1                False  
2                False  
3                False  
4                False  
..                 ...  
145               True  
146               True  
147               True  
148               True  
149               True  

[150 rows x 6 columns]

In [91]:
a['species_versicolor'] = a["species_versicolor"].astype(int)

In [92]:
a['species_virginica'] = a["species_virginica"].astype(int)

In [93]:
a

sepal_length  sepal_width  petal_length  petal_width  species_versicolor  \
0             5.1          3.5           1.4          0.2                   0   
1             4.9          3.0           1.4          0.2                   0   
2             4.7          3.2           1.3          0.2                   0   
3             4.6          3.1           1.5          0.2                   0   
4             5.0          3.6           1.4          0.2                   0   
..            ...          ...           ...          ...                 ...   
145           6.7          3.0           5.2          2.3                   0   
146           6.3          2.5           5.0          1.9                   0   
147           6.5          3.0           5.2          2.0                   0   
148           6.2          3.4           5.4          2.3                   0   
149           5.9          3.0           5.1          1.8                   0   

     species_virginica  
0                    0  
1                    0  
2                    0  
3                    0  
4                    0  
..                 ...  
145                  1  
146                  1  
147                  1  
148                  1  
149                  1  

[150 rows x 6 columns]

In [94]:
a['species_virginica'].value_counts()

species_virginica
0    100
1     50
Name: count, dtype: int64

In [95]:
a['species_versicolor'].value_counts()

species_versicolor
0    100
1     50
Name: count, dtype: int64

In [98]:
df = pd.DataFrame({'name':["Swift", 'Verna', 'Polo','Creta'],
                  'Brand': ['Suzuki', 'Hyundai', 'vw', 'Hyundai'],
                  'Color' : ['Red', 'White', 'Black', 'White']})

In [99]:
df

name    Brand  Color
0  Swift   Suzuki    Red
1  Verna  Hyundai  White
2   Polo       vw  Black
3  Creta  Hyundai  White

In [103]:
df_one_hot = pd.get_dummies(df, columns = ["Brand", "Color"], prefix = "is" )

In [104]:
df_one_hot

name  is_Hyundai  is_Suzuki  is_vw  is_Black  is_Red  is_White
0  Swift       False       True  False     False    True     False
1  Verna        True      False  False     False   False      True
2   Polo       False      False   True      True   False     False
3  Creta        True      False  False     False   False      True

In [112]:
# Ordinal Encoding -- can use in case you know the order like small -- 1, medium --2 because machine does not know any difference it can assign any values with knowing the size

In [113]:
data = {'Size':['Small','Medium','Large']}

In [114]:
df = pd.DataFrame(data)

In [115]:
df

Size
0   Small
1  Medium
2   Large

In [116]:
size_mapping = {'small':1, 'medium':2,'large':3}

In [117]:
df['Size_Encoded'] = df['Size'].map(size_mapping)

In [118]:
df

Size  Size_Encoded
0   Small           NaN
1  Medium           NaN
2   Large           NaN

In [119]:
# can use this lib. 

from sklearn.preprocessing import OrdinalEncoder

encoder = OrdinalEncoder()

Size =  ['Small','Meduim','Large'] 

In [120]:
Size = np.array(Size).reshape(-1,1)

encoded = encoder.fit_transform(Size)

encoded

array([[2.],
       [1.],
       [0.]])